const searchBar = document.getElementById("searchBar");
const listAll = document.getElementById("listAll");
const listToggle = document.querySelector(".list-toggle");
const data = [
  // Forms
  {
    id: 100,
    formNumber: "100",
    orderNumber: 100,
    childForms: [
      {
        id: 1,
        formNumber: "1",
        orderNumber: 1,
        childForms: [],
        hrefAddress: "/forms/1",
        uname: null,
        formActiveName: "Посевные семена хлопчатника",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 2,
        formNumber: "2",
        orderNumber: 2,
        childForms: [],
        hrefAddress: "/forms/2",
        uname: null,
        formActiveName: "Посевные семена риса",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 3,
        formNumber: "3",
        orderNumber: 3,
        childForms: [],
        hrefAddress: "/forms/3",
        uname: null,
        formActiveName: "Минеральное удобрение",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 4,
        formNumber: "4",
        orderNumber: 4,
        childForms: [],
        hrefAddress: "/forms/4",
        uname: null,
        formActiveName: "Справка по расходу дизельного топлива",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 5,
        formNumber: "5",
        orderNumber: 5,
        childForms: [],
        hrefAddress: "/forms/5",
        uname: null,
        formActiveName:
          "Затраты дизельного топлива на не основной вид деятельности",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 6,
        formNumber: "6",
        orderNumber: 6,
        childForms: [],
        hrefAddress: "/forms/6",
        uname: null,
        formActiveName: "Оплата наёмным работником ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 7,
        formNumber: "7",
        orderNumber: 7,
        childForms: [],
        hrefAddress: "/forms/7",
        uname: null,
        formActiveName: "Накт пул таркатиш журнали",
        starred: false,
        statusName: "Пассивный",
      },
      {
        id: 8,
        formNumber: "8",
        orderNumber: 8,
        childForms: [],
        hrefAddress: "/forms/8",
        uname: null,
        formActiveName: "Запчасты",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 9,
        formNumber: "9",
        orderNumber: 9,
        childForms: [],
        hrefAddress: "/forms/9",
        uname: null,
        formActiveName: "Электроэнергия",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 10,
        formNumber: "10",
        orderNumber: 10,
        childForms: [],
        hrefAddress: "/forms/10",
        uname: null,
        formActiveName: "Налог на землю",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 11,
        formNumber: "11",
        orderNumber: 11,
        childForms: [],
        hrefAddress: "/forms/11",
        uname: null,
        formActiveName: "Заработная  плата",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 12,
        formNumber: "12",
        orderNumber: 12,
        childForms: [],
        hrefAddress: "/forms/12",
        uname: null,
        formActiveName: "Проценты по кредитом и амортизация",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 13,
        formNumber: "13",
        orderNumber: 13,
        childForms: [],
        hrefAddress: "/forms/13",
        uname: null,
        formActiveName: "Затраты на продукты питания",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 14,
        formNumber: "14",
        orderNumber: 14,
        childForms: [],
        hrefAddress: "/forms/14",
        uname: null,
        formActiveName: "Услуги биолоборатории",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 15,
        formNumber: "15",
        orderNumber: 15,
        childForms: [],
        hrefAddress: "/forms/15",
        uname: null,
        formActiveName:
          "Затраты на привлечение техники от сторонних организаций",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 16,
        formNumber: "16",
        orderNumber: 16,
        childForms: [],
        hrefAddress: "/forms/16",
        uname: null,
        formActiveName:
          "Компенсация затрат по ликвидированным фермерским хозяйствам",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 24,
        formNumber: "24",
        orderNumber: 24,
        childForms: [],
        hrefAddress: "/forms/24",
        uname: null,
        formActiveName: "Ekinlardan olinadigan daromadlar",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 25,
        formNumber: "25",
        orderNumber: 25,
        childForms: [],
        hrefAddress: "/forms/25",
        uname: null,
        formActiveName: "Благотворительность",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 26,
        formNumber: "26",
        orderNumber: 26,
        childForms: [],
        hrefAddress: "/forms/26",
        uname: null,
        formActiveName: "Прочие расходы",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 17,
        formNumber: "17",
        orderNumber: 17,
        childForms: [],
        hrefAddress: "/forms/17",
        uname: null,
        formActiveName: "Затраты на транспортировку",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 18,
        formNumber: "18",
        orderNumber: 18,
        childForms: [],
        hrefAddress: "/forms/18",
        uname: null,
        formActiveName: "Затраты на горючее",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 19,
        formNumber: "19",
        orderNumber: 19,
        childForms: [],
        hrefAddress: "/forms/19",
        uname: null,
        formActiveName: "Затраты на сбор урожая",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 20,
        formNumber: "20",
        orderNumber: 20,
        childForms: [],
        hrefAddress: "/forms/20",
        uname: null,
        formActiveName: "Химические препараты",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 21,
        formNumber: "21",
        orderNumber: 21,
        childForms: [],
        hrefAddress: "/forms/21",
        uname: null,
        formActiveName: "Посевные семена пшеницы",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 22,
        formNumber: "22",
        orderNumber: 22,
        childForms: [],
        hrefAddress: "/forms/22",
        uname: null,
        formActiveName: "Посевные семена других растекий",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 23,
        formNumber: "23",
        orderNumber: 23,
        childForms: [],
        hrefAddress: "/forms/23",
        uname: null,
        formActiveName: "Оплата наёмным работникам  за сбор хлопка",
        starred: false,
        statusName: "Активный",
      },
    ],
    hrefAddress: null,
    uname: null,
    formActiveName: "Форма",
    starred: false,
    statusName: "Активный",
  },
  // Reports
  {
    id: 101,
    formNumber: "101",
    orderNumber: 101,
    childForms: [
      {
        id: 102,
        formNumber: "102",
        orderNumber: 102,
        childForms: [],
        hrefAddress: null,
        uname: null,
        formActiveName: "РАСЧЕТ ОБЩЕЙ СТОИМОСТИ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 103,
        formNumber: "103",
        orderNumber: 103,
        childForms: [],
        hrefAddress: null,
        uname: null,
        formActiveName: "ВЫБОР СЧЕТА ЗАТРАТ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 104,
        formNumber: "104",
        orderNumber: 104,
        childForms: [],
        hrefAddress: null,
        uname: null,

        formActiveName: "ОБЩИЕ ЗАТРАТЫ АГРОКЛАСТЕРА",
        starred: false,
        statusName: "Активный",
      },
    ],
    hrefAddress: null,
    uname: null,
    formActiveName: "Отчеты",
    starred: false,
    statusName: "Активный",
  },
  // Information
  {
    id: 110,
    formNumber: "110",
    orderNumber: 110,
    childForms: [
      {
        id: 111,
        formNumber: "111",
        orderNumber: 111,
        childForms: [],
        hrefAddress: "/references/def_references",
        uname: null,
        formActiveName: "АНАЛОГИЧНАЯ ИНФОРМАЦИЯ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 112,
        formNumber: "112",
        orderNumber: 112,
        childForms: [],
        hrefAddress: "/references/brigades",
        uname: null,
        formActiveName: "СПИСОК БРИГАДА",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 113,
        formNumber: "113",
        orderNumber: 113,
        childForms: [],
        hrefAddress: "/references/territories",
        uname: null,
        formActiveName: "СПИСКИ РЕГИОНОВ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 114,
        formNumber: "114",
        orderNumber: 114,
        childForms: [],
        hrefAddress: "/references/forms",
        uname: null,
        formActiveName: "СПИСОК ФОРМ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 115,
        formNumber: "115",
        orderNumber: 115,
        childForms: [],
        hrefAddress: "/references/techniques",
        uname: null,
        formActiveName: "СПИСОК ТЕХНИКИ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 116,
        formNumber: "116",
        orderNumber: 116,
        childForms: [],
        hrefAddress: "/references/standard-consumptions",
        uname: null,
        formActiveName: "СТАНДАРТ ТЕХНИКИ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 117,
        formNumber: "117",
        orderNumber: 117,
        childForms: [],
        hrefAddress: "/references/changing-territories",
        uname: null,
        formActiveName: "ПЕРЕРАСПРЕДЕЛЕНИЕ ЗЕМЕЛЬНОЙ ПЛОЩАДИ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 118,
        formNumber: "118",
        orderNumber: 118,
        childForms: [],
        hrefAddress: "/references/ratio-crops",
        uname: null,
        formActiveName: "КОЭФФИЦИЕНТ ОБРЕЗКИ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 119,
        formNumber: "119",
        orderNumber: 119,
        childForms: [],
        hrefAddress: "/references/meter",
        uname: null,
        formActiveName: "СЧЁЧИК",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 120,
        formNumber: "120",
        orderNumber: 120,
        childForms: [],
        hrefAddress: "/references/credit-report",
        uname: null,
        formActiveName: "КРЕДИТНАЯ ИНФОРМАЦИЯ",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 121,
        formNumber: "121",
        orderNumber: 121,
        childForms: [],
        hrefAddress: "/references/currency-report",
        uname: null,
        formActiveName: "КУРС",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 122,
        formNumber: "122",
        orderNumber: 122,
        childForms: [],
        hrefAddress: "/references/annual-plans",
        uname: null,
        formActiveName: "ГОДОВОЙ ПЛАН СН/ГК",
        starred: false,
        statusName: "Активный",
      },
      {
        id: 123,
        formNumber: "123",
        orderNumber: 123,
        childForms: [],
        hrefAddress: "/references/min-price-crop",
        uname: null,
        formActiveName: "Таннарх",
        starred: false,
        statusName: "Активный",
      },
    ],
    hrefAddress: null,
    uname: null,
    formActiveName: "Info",
    starred: false,
    statusName: "Активный",
  },
  // Admins
  {
    id: 130,
    formNumber: "130",
    orderNumber: 130,
    childForms: [],
    hrefAddress: "/user-list",
    uname: null,
    formActiveName: "АДМИН ПАНЕЛЬ",
    starred: false,
    statusName: "Активный",
  },
  // Saved
  {
    id: 131,
    formNumber: "131",
    orderNumber: 131,
    childForms: [],
    hrefAddress: "/user-list",
    uname: null,
    formActiveName: "Saved",
    starred: false,
    statusName: "Активный",
  },
];
const items = [];

data.map(function (forms) {
  forms.childForms.forEach(function (form) {
    items.push(form);
  });
});

if (searchBar != null) {
  searchBar.addEventListener("keyup", (e) => {
    const searchString = e.target.value.toLowerCase();
    if (searchString) {
      const filteredForms = items.filter((form) => {
        return (
          form.formActiveName.toLowerCase().includes(searchString) ||
          form.formNumber.toLowerCase().includes(searchString)
        );
      });
      listToggle.classList.remove("d-none");
      displayForms(filteredForms);
    } else {
      listToggle.classList.add("d-none");
    }
  });
}

const displayForms = (forms) => {
  const htmlString = forms
    .map((form) => {
      return `
      <li class="item">
        <a class="link" href="${form.hrefAddress}">${form.formNumber}. ${form.formActiveName}</a>
      </li>
    `;
    })
    .join("");
  listAll.innerHTML = htmlString;
};
displayForms(items);
